### ISSUE TITLE
"Admin To-Do" page

### ISSUE THREAD

**Issue by PhantomWatson** [BallStateCBER/cri#32]
Concept
---------
- A list of all communities and current actions that can be taken by administrators
- Different styling for "thing that an admin can do now" versus "thing that we're waiting for the client to do"
- For each community, the following list is checked in order and the first applicable item is displayed

Actions
--------
- [x] Ready to add client to community (no clients)
- [x] Waiting for client to purchase Step Two survey
- [x] Ready to advance community to Step Two (survey purchased)
- [x] Ready to create Step Two survey (community in Step Two, survey not created yet)
- [x] Ready to activate Step Two survey (created, no responses, not active)
- [x] Waiting for Step Two invitations to be sent (survey active, no invitations sent)
- [x] Waiting for Step Two invitations to be responded to (survey active, invitations sent, no responses)
- [x] Waiting for sufficient Step Two/Three survey responses to be collected (invitations sent, responses received, survey not yet ready to be deactivated)
      Also display the number of responses, invitation/response ratio, and days since last response
      Also display link for deactivating survey
- [x] Ready to deactivate survey (criteria could include time active, total responses, or invitation vs. response ratio)
- [x] Ready to schedule Presentation A (Step Two survey responses received and deactivated)
- [x] Waiting for Presentation A to conclude
- [x] Ready to schedule Presentation B (Presentation B purchased)
- [x] Waiting for Presentation B to conclude
- [x] Waiting for client to purchase organizations survey
- [x] Ready to advance community to Step Three (step three survey purchased)
- [x] Ready to create Step Three survey
- [x] Ready to activate Step Three survey (in Step Three, created, no responses, not active)
- [x] Ready to schedule Presentation C (Step Three survey responses received and deactivated)
- [x] Waiting for Presentation C to conclude
- [x] Ready to schedule Presentation D (Presentation D purchased)
- [x] Waiting for Presentation D to conclude
- [x] Waiting for client to purchase policy development (not purchased yet)
- [x] Ready to advance to Step Four (survey deactivated, all presentations concluded, policy development purchased)

Questions:
-----------
- Should **concluding** all of a step's presentations be a prerequisite for advancing to the next step, or should **scheduling** all presentations be sufficient? (Srikant says "concluding")

**Comment by bjpatterson** [comment]
**Ready to advance community to Step X** - Is there a good reason not to automatically advance a community once they've paid (and in the case of step 3, presentations A and B have passed)?  It seems like a rubber stamp that could just as well be automatic.

Would it make sense to include any of CBER's tasks in the site (Economic Data collected, Presentations/Handouts Completed)?  It would be nice to track this _somewhere_ on the site, and it would give us a mechanism for letting ICI know that presentation materials are ready without assumptions or emails.  Data can be collected asynchronously any time after the first payment is made, but before the first presentation.  Presentations need to be built after surveys close, but before the presentation is given.

The rest of this looks good to me, and seems to include all the major blockers in the CRI process.

**Comment by PhantomWatson** [comment]
> Ready to advance community to Step X - Is there a good reason not to automatically advance a community once they've paid (and in the case of step 3, presentations A and B have passed)? It seems like a rubber stamp that could just as well be automatic.

If there's agreement among everyone that this doesn't have to be manually done anymore, this could be set up as a check that happens once per day. When the idea of automating this was originally brought up (maybe a year or two ago), there was some apprehension.

The only complication that I can think of is if a community doesn't purchase an optional **_BONUS PRESENTATION®™_** until after their mandatory presentation has concluded. They'll be advanced to (for example) Step Three and *then* schedule and conduct their optional Step Two presentation. Which might not be a big deal.

**Comment by PhantomWatson** [comment]
> Would it make sense to include any of CBER's tasks in the site (Economic Data collected, Presentations/Handouts Completed)? It would be nice to track this somewhere on the site, and it would give us a mechanism for letting ICI know that presentation materials are ready without assumptions or emails.

Yeah, if ICI folks would definitely use the website to keep up-to-date on CBER's progress on these tasks, then it would be worth it. The website could also automatically send emails to ICI when tasks are reported as being completed.

**Comment by bjpatterson** [comment]
> The only complication that I can think of is if a community doesn't purchase an optional BONUS PRESENTATION®™ until after their mandatory presentation has concluded.

I think the money should give this away. If a community pays for Presentations A and C (and **not** B), we can advance them after presentation A with a fair degree of confidence.  If they've paid for B, we obviously don't want to advance them until presentation B has been concluded.  We *never* want to advance a community before they've paid for the advancement.  It's not quite foolproof, but this logic should cover pretty much all use cases.  The potential errors seem rather unlikely unless someone is intentionally trying to break the process.
