### ISSUE TITLE
Improve the scope and specificity of the to-do list

### ISSUE THREAD

**Issue by bjpatterson** [BallStateCBER/cri#51]
## Description:
The to-do list looks like a great place for daily community management.  There are a few extra details that would help facilitate use of this page as a command center.

## Potential Tasks:
- [x] Add a *"waiting since ..."* snippet to the "waiting for client to ..." statuses
- [ ] Allow for grouping of communities by status (e.g. "I want to see all communities that are administering a survey.")
- [x] Filter out communities that are "Done" with CRI (related to #50, #53)
- [x] Track ICI tasks
- [x] Distinguish between ICI and CBER tasks
- [x] defDone: The to-do list can be used as a one-stop shop for running most/all of CRI

**Comment by PhantomWatson** [comment]
Specifics about how **"Waiting since..."** values are calculated:
- Waiting for client to purchase officials questionnaire
  since community was added to the website
- Waiting for client to send questionnaire invitations
  since survey was activated
- Waiting for responses to questionnaire
  since first invitation went out
- Waiting for client to purchase or opt out of optional presentation
  since mandatory presentation completed
- Waiting for client to purchase or opt out of organizations questionnaire
  since most recent purchased presentation completed
- Waiting for client to purchase or opt out of policy development
  since most recent purchased presentation completed

**Comment by bjpatterson** [comment]
Sounds perfect, I'll stand behind these calculations
