### ISSUE TITLE
Marking communities as "Done"

### ISSUE THREAD

**Issue by bjpatterson** [BallStateCBER/cri#53]
## Description:
Several Communities have gone through the first phases of CRI, and have no intent to continue.  It would be nice to mark these communities in some way to stop them from showing through on the to-do list, among other places. Related to #50

## Potential Tasks:
- [x] Allow communities to be marked as "Done" with CRI
  - [x] Client (or admin posing as client) can opt community out of further participation
  - [x] Admin can mark a community as _inactive_ but not explicitly opted-out
    - [x] Warn before marking a community as inactive before delivering something that's been paid for
    - [x] Client is shown a "you've been inactive for awhile, would you like to resume participation in CRI?" screen if logging in to an inactive community
    - [x] Clients re-activating their own communities is logged in the [Activity Log](https://cri.cberdata.org/admin/activity-records)
- [x] Distinguish between "paid for policy dev" and "received policy dev" states to help define "graduated"
- [x] Filter "Done" communities out of the to-do list
- [x] Hide "Done" communities from the "Manage Communities" page, add button to show these communities
- [x] defDone: Communities can be marked as "Done", which suppresses them where appropriate

**Comment by PhantomWatson** [comment]
I'd like to make sure that we'll be able to easily distinguish between communities that have "graduated" the program and "dropped out", in case that distinction is ever important to us (like generating "graduation rate" stats, etc.).

**One way we could do this:**
- Communities are marked as simply "active" or "inactive"
- Communities who have "graduated" would be any that are "inactive" and on Step Four (in fact, we could automatically deactivate a community when they are advanced to Step Four)
- Communities who have "dropped out" would be inactive ones who have not yet been advanced to Step Four

**Questions:**
- Should clients be allowed to deactivate their own communities (drop out of the program)?
- How do we deal with client accounts for inactive communities? Should they have access to the client home page to see what their progress was? Should they be able to reactivate their communities on their own?
- Should "graduated" and "dropped out" communities be included in reports?

**Comment by bjpatterson** [comment]
This might take a little discussion.
For the most part, any community that completes presentation A has "completed" CRI (from OCRA's point of view.)  If a community opts out of B, C, D, I'm not sure whether we would classify them as a graduate or a dropout.  What might be more useful on our end is a completion rate for each presentation, which might not even need a graduate/dropout status.

**Comment by bjpatterson** [comment]
> we could automatically deactivate a community when they are advanced to Step Four

The only drawback here is that once they've been deactivated, they no longer show up on the To-Do list. ICI would probably like to know that a community is a candidate for policy development. (Although there's a strong chance that they'd already be intensely aware without the website telling them so.)

**Comment by PhantomWatson** [comment]
> If a community opts out of B, C, D, I'm not sure whether we would classify them as a graduate or a dropout

If a community opts out of presentation B and declines to pay to be advanced to Step Three at all (so no Presentations C or D), then they would be deactivated and end up in the "dropout" category, distinct from the "graduated" category because they would have the option to resume their participation in the future.

> The only drawback here is that once they've been deactivated, they no longer show up on the To-Do list.

The order of events could actually go like this:
1. Community completes Step Three
2. Community pays for policy development and gets automatically advanced to Step Four
3. **A new "develop and deliver policy recommendation" task tracked by the website is checked off** (CBER or ICI?)
4. The community is deactivated and ascends into CRI Valhalla (and no longer shows up on the to-do list, etc.)

**Comment by bjpatterson** [comment]
This works for me, but we'll need to be careful about how we report things.  A community that opts out after completing presentation B might be a dropout from our point of view (because they have the option to resume later), but a graduate from OCRA's point of view (because they completed Presentation A).  Perhaps it warrants multiple status columns, a `CRI_Status` and `OCRA_Status`, to keep the logic from getting out of hand?

**Comment by PhantomWatson** [comment]
It sounds like all communities, regardless of status, should be included in reports instead of "inactive" communities being filtered out.

And if OCRA isn't interested in anything that takes place after Presentation A, then the OCRA report's "status" column could simply stop reporting on anything else after the "presentation A given" condition has been met.

The "graduated" vs. "dropped out" statuses could just be used in the CRI admin reports.

**Comment by bjpatterson** [comment]
Yes, I think reports should show all communities, but the To-Do list in particular should intelligently filter out inactive communities.

I'm not sure what we want to do with the OCRA reports.  The OCRA money is tied to presentation A, but in an effort to keep them engaged (¿and potentially convince them to fund further presentations?), we might want to report beyond that point.

**Comment by PhantomWatson** [comment]
I propose this:

**Communities:** Can be marked by an administrator (maybe clients too) as inactive at any point
**To-do lists:** Filters out inactive communities
**OCRA reports:** No change from current setup
**Admin reports:** The status of inactive communities is shown as either "graduated" or "dropped out"
**Map:** No communities filtered out, no special styling for dropouts

**Comment by bjpatterson** [comment]
Sounds good. I recommend that the ability to deactivate be accessible from the To-do list (or it probably won't get used properly).

Any community with "Waiting for client to purchase..." as a to-do status should have a corresponding option to deactivate the community (likely with an "are you sure?" confirmation).

(I lean towards not letting clients formally deactivate themselves. That seems like it should be an actual conversation between a community and ICI.)
